env:
  secure: peZVlODach6zWjiK42Dl0lzawD8nGZCVq0TnZnAgreHLa01snuzVNQ9IzeFqMNQK7du4dYdyOk1in7Pq4etAybFPBjieknnRdBaVR90doOiYrgsRi7gLhlV7VQwjkfQiVbG9vhfRJ2+GnJ/n38j5QTrYXEkQYOTf6u7lu9gKXIeto5RtpJL258Ebb08POqxrCrnzyID3ntErNsUM6bCqOU0HiDfyuU4znomRo8Drxzl75wI5q1CMzWGbukM55Yz+kTdVpwQFsLfgNtpks2QX4ELKuAa5HB9+tB0+rxUKVtY8C2DfjDUm7Cox2AIcORSMAvQnWodZe0VuhrkuYmI1rloaYkddSrxY7uoeeVZ8eBCzXFS4qTlDC+vyrJ3JOhKlDtpTGHgCiREiuIEEu+VPBb0I12BPTOqs3cPe9JP1riUctL44icpwFDB0bnJMvIXhShPwoO7STtnObSu2UZxtDcnjHYk+YJ0xfKXYJD0lcs6zEK8sboBYbPfBPZXW5fGmxDI6HD+tcMxVRDV6roUKmyMkpT4oz2z7XV2LXtr8gUbyM92M3swLSfPpev5zVH2ZTBXjinsocqJcqBOkTYTnF091CTGg4tBppWAP1WqSV6kBQWjGe+thhvVQs8FAIaRGumtogly9+6sLoZhY1hw5C7mWq50MssERjSE9kxp+vVo=
  secure: l4fUeutKvBsJaHNU+7a4ivGKrpfsiJgLH08oG9TkpL8Slfy4yROsagSvxDGSwPDJrvawJEAOxzjbAOj/QLxqr3oRBvHaJt/ieh14G62d9F3d+OXMwrbly5GUr9MekHL8qkfzfYyjzWR/W6tcOMJ5NBqvBY5bfE+Cxk0bEJNp7+VPbQqSd91/cIepWMEBhKrcmokqMH1dZyMkxLttT5cAMwHOojrlAfB/ZmZG1l/Czf2kpCYTAyUvkzfSSp270RMn7ylE9Nzsp/OCzY+p8noHqMzabvASvsv9/B9gPthf7mRsxvxV8gdlku/c34/tBc23Jt3DslCY69vaccQu/0zYtIurgmsrmPDGuNbCm61RxvexU9AMYgj+Cdc6CbkbkH5Vy2qdyUyhzdJjKAkLai3pFpZHNz5lA7SqBcEvn0NKqk/9Y+bmpLicm0j85Nz+1I9NAMM10FccmvzaUuzw2iN+ExVZsjz7qB4G6Cs+pOuZZfVa8CrzYiP2p7b66LmYGoBL4cmlJvs1vjGFUVJazi66TI6FKikSQ5j0J5vE1UAW3ETkiWifrm/u3+SxMfBE9R+jN5FZt9k4bVJmFQohzEweIIegMEByJBcZqdAZYpocpikRCtoYzuBm4kEufGG1eZLVnm0EH225Boakq/LLKZlhvzPs9ea59+OWSB7U153beDI=

language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
git:
  submodules: false
script:
- yarn
- yarn test
- yarn build
deploy:
  provider: pages
  all_branches: true
  skip_cleanup: true
  target_branch: ci-gh-pages
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  commit_message: "[ci skip] published by TravisCI"
  on:
    all_branches: true
notifications:
    slack: samuraitruong:FXQZ2yjmeEVZEN2E1nWyAmRp
