# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
general:
  branches:
    only:
      - master
    ignore:
      - gh-pages
notify:
  webhooks:
    - url: https://hooks.slack.com/services/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
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    branches:
      ignore:
        - gh-pages
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: git config --global user.email "samuraitruong@hotmail.com"
      - run: git config --global user.name "Truong Nguyen CI"
      - run: 
          name: Run UI test
          command: yarn test
          environment:
            REACT_APP_WEB_API_URL: https://dummy/
      #- run: 
      #    name: Deploy to GH 
      #    command: yarn deploy
  deployment:
    production: # just a label; label names are completely up to you
      branch: master
      commands:
        - yarn deploy